import { useEffect, useState } from "react";
import { createTransportCompany, deleteTransportCompany, getAdminTransportCompanies, getNigerianDeliveryStates, importStarterTransportCompanies, updateTransportCompany } from "../services/api";

const empty = { name: "", states: [], active: true };

export default function AdminTransportCompanies() {
  const [companies, setCompanies] = useState([]);
  const [states, setStates] = useState([]);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState(null);
  const [message, setMessage] = useState("");
  const load = async () => { try { const [items, rates] = await Promise.all([getAdminTransportCompanies(), getNigerianDeliveryStates()]); setCompanies(items); setStates(rates.map((rate) => rate.state)); } catch (error) { setMessage(error.message || "Unable to load transport companies."); } };
  useEffect(() => { load(); }, []);
  const toggleState = (state) => setForm((current) => ({ ...current, states: current.states.includes(state) ? current.states.filter((item) => item !== state) : [...current.states, state] }));
  async function save(event) { event.preventDefault(); try { if (editing) await updateTransportCompany(editing, form); else await createTransportCompany(form); setForm(empty); setEditing(null); setMessage("Transport company saved."); load(); } catch (error) { setMessage(error.message || "Unable to save transport company."); } }
  async function importStarter() { try { const result = await importStarterTransportCompanies(); setMessage(result.message); load(); } catch (error) { setMessage(error.message || "Unable to import starter transport companies."); } }
  return <div className="page"><h1>Transport Companies</h1><p className="muted">Add the companies customers can collect from. Select every state each company serves; checkout only shows companies assigned to the customer’s selected state.</p><button type="button" className="secondary-button" onClick={importStarter}>Import common transport companies</button><p className="muted">This adds common operators to your active shipping states. Review and adjust each company’s state coverage afterwards.</p><form className="form" onSubmit={save}><input required placeholder="Transport company or park name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><fieldset className="payment-methods"><legend>States served</legend><div className="wizard-grid">{states.map((state) => <label key={state} className="wizard-checkbox"><input type="checkbox" checked={form.states.includes(state)} onChange={() => toggleState(state)} /><span>{state}</span></label>)}</div></fieldset><label className="wizard-checkbox"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /><span>Show at checkout</span></label><button className="primary">{editing ? "Update transport company" : "Add transport company"}</button>{editing && <button type="button" onClick={() => { setForm(empty); setEditing(null); }}>Cancel</button>}</form>{message && <p className="inline-toast success">{message}</p>}<section style={{ marginTop: 32 }}><h2>Configured companies</h2><div className="grid">{companies.map((company) => <article className="card" key={company._id}><h3>{company.name}</h3><p>{company.active ? "Active at checkout" : "Hidden from checkout"}</p><p className="muted">{company.states.join(", ") || "No state assigned"}</p><button onClick={() => { setEditing(company._id); setForm({ name: company.name, states: company.states || [], active: company.active }); }}>Edit</button><button className="btn-danger" onClick={async () => { await deleteTransportCompany(company._id); load(); } }>Delete</button></article>)}</div></section></div>;
}
