import Navbar from "../components/Navbar";

const policyLinks = <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 16 }}><a className="cta" href="/refund-policy">Refund & Returns</a><a className="cta" href="/terms-conditions">Terms & Conditions</a><a className="cta" href="/contact">Contact Support</a></div>;

export default function PrivacyPolicy() {
  return <><Navbar /><main className="page" style={{ maxWidth: 900, margin: "0 auto", padding: "40px 20px" }}>{policyLinks}<h1>Privacy Policy</h1><p style={{ color: "#666", marginBottom: 20 }}>Last updated: 2026-09-08</p>
    <h2>Who is responsible for your information</h2><p>RESYIN Publications operates this website and is responsible for the personal information described in this policy. Contact us at <a href="mailto:info@resyinpublications.com">info@resyinpublications.com</a>, WhatsApp +2349041441646 or +2348034621513, or through our <a href="/contact">Contact Support</a> page.</p>
    <h2>Information we collect</h2><ul><li>Account details such as your name, email address, phone number, password credentials, and profile information.</li><li>Order and delivery details such as books ordered, delivery address, country, city, contact number, order history, and support messages.</li><li>Payment and refund records, including payment reference, amount, payment status, and transaction date. Card and bank credentials are processed by Paystack and are not stored by us.</li><li>Information you submit through contact, enquiry, review, registration, publisher application, or support forms, including files or photos you choose to send us.</li><li>Technical information needed to operate and secure the website, such as device, browser, IP address, session information, and push-notification subscription data if you enable notifications.</li></ul>
    <h2>How we use information</h2><ul><li>To create and manage accounts, fulfil book orders, process payments and refunds, deliver books, and provide customer support.</li><li>To send necessary order, account-verification, password-reset, security, and service communications.</li><li>To prevent fraud, protect our services, resolve disputes, maintain records, and comply with legal or accounting obligations.</li><li>To improve our bookstore, website, and customer experience. We do not sell personal information.</li></ul>
    <h2>Payments and service providers</h2><p>We use Paystack to process online payments. When you pay, Paystack processes the payment information under its own privacy notice and security controls. We may also use hosting, cloud storage, email, notification, delivery, and customer-support providers where necessary to run our services. We share only the information reasonably needed for the service they provide or where law requires it.</p>
    <h2>Google Sign-In and Google data</h2><p>If you choose Google Sign-In, we receive the basic account information you approve, such as your name, email address, and profile image, to authenticate you and provide your RESYIN Publications account. We do not use Google user data for advertising, sell it, or use it to determine eligibility for credit, employment, housing, insurance, or other sensitive decisions.</p><p>Our official email system may use Gmail API credentials only to send account-verification, password-reset, and important service emails from our official support account. This permission is used for transactional email delivery and is not used to read, search, store, or access the contents of customers’ Gmail inboxes.</p>
    <h2>Retention and security</h2><p>We retain information only for as long as reasonably needed to provide services, maintain records, resolve disputes, prevent fraud, meet legal obligations, and enforce our agreements. We use reasonable organisational and technical safeguards; however, no online system can be guaranteed completely secure. Keep your password private and contact us promptly if you believe your account has been accessed without permission.</p><p>We use secure, time-limited order-confirmation links to help customers access order information after checkout. These links are designed to protect order and delivery information and may expire or be usable only once.</p>
    <h2>Account deletion and retention</h2><p>Users may request deletion of their account. Where an account deletion request is received, we may review it before action is taken, and we may keep certain records where required for legal, tax, fraud, delivery, support, or operational reasons. This includes records needed to fulfil book orders, protect against disputes or abuse, meet legal obligations, or maintain the integrity of our platform.</p><p>In some cases, an account may be temporarily deactivated or marked for deletion before permanent removal. We may also permanently delete accounts after an approved retention period or when an administrator approves immediate permanent deletion. When a user account is permanently deleted, we remove the user record and related session or cart data, where applicable, while retaining only information that we are legally required or reasonably required to keep.</p>
    <h2>Your choices and rights</h2><p>Subject to applicable law, you may ask us to access, correct, delete, or restrict certain personal information, or object to certain processing. You can opt out of non-essential marketing communications using the unsubscribe option where provided or by contacting us. You can disable browser or device notifications at any time in your device or browser settings.</p>
    <h2>Policy changes</h2><p>We may update this policy when our practices or legal obligations change. We will publish the current version on this page and update the date above.</p>
  </main></>;
}
