import Navbar from "../components/Navbar";

const policyLinks = <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 16 }}><a className="cta" href="/privacy-policy">Privacy Policy</a><a className="cta" href="/terms-conditions">Terms & Conditions</a><a className="cta" href="/contact">Contact Support</a></div>;

export default function RefundPolicy() {
  return <><Navbar /><main className="page" style={{ maxWidth: 900, margin: "0 auto", padding: "40px 20px" }}>{policyLinks}<h1>Refund & Returns Policy</h1><p style={{ color: "#666", marginBottom: 20 }}>Last updated: 2026-09-08</p>
    <h2>Our promise</h2><p>This policy explains how RESYIN Publications handles returns, replacements, and refunds for physical books bought on this website. It applies alongside your rights under applicable Nigerian consumer-protection law; nothing here removes rights that cannot lawfully be excluded.</p>
    <h2>Before you buy</h2><p>Each product page should show the product description, price, availability, and relevant product information. Delivery charges and the delivery estimate for your selected destination are shown at checkout before payment. Please check these details and contact us before ordering if you need help choosing a product.</p>
    <h2>When a return, replacement, or refund may be available</h2><ul><li><strong>Damaged, defective, incorrect, incomplete, or materially misdescribed items:</strong> contact us within 7 days of delivery with your order number, photos, and a short description of the issue. We will assess the issue and, where appropriate, arrange a replacement, repair, return, or refund.</li><li><strong>Change-of-mind requests:</strong> contact us within 7 days of delivery. We may accept an unopened, unused item in its original sealed packaging, subject to inspection and any applicable legal rights.</li></ul>
    <h2>How to request help</h2><ol><li>Email <a href="mailto:info@resyinpublications.com">info@resyinpublications.com</a>, use our <a href="/contact">Contact Support</a> page, call or WhatsApp +2349041441646 or +2348034621513.</li><li>Include your order number, the product name, the reason for your request, and clear photos where relevant.</li><li>Wait for written return instructions before sending an item back. Do not return goods to a location unless we confirm the return address and method.</li></ol>
    <h2>Return delivery costs</h2><p>If the item is faulty, damaged on arrival, incorrect, or not as described, RESYIN Publications will provide reasonable return instructions and cover or reimburse the approved return-delivery cost where required. For an approved change-of-mind return, the customer is responsible for return delivery costs unless we agree otherwise. Original delivery charges are refunded only where required by law or where the issue was our error.</p>
    <h2>Refund timing and method</h2><p>Once a return is received or an issue is verified, we will notify you of the outcome. Approved refunds are sent to the original payment method where possible. Payment-provider and bank processing times vary; our usual processing target is 7–14 business days after approval. If a replacement is agreed, we will confirm the dispatch plan and any delivery estimate.</p>
    <h2>Orders that have not arrived</h2><p>If your order has not arrived by the displayed delivery estimate, please contact us with your order number. We will investigate with the delivery provider and keep you updated before deciding the appropriate remedy.</p>
    <h2>Contact and business details</h2><p>RESYIN Publications. </p>
  </main></>;
}
