import Navbar from "../components/Navbar";

const policyLinks = <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 16 }}><a className="cta" href="/privacy-policy">Privacy Policy</a><a className="cta" href="/refund-policy">Refund & Returns</a><a className="cta" href="/contact">Contact Support</a></div>;

export default function TermsConditions() {
  return <><Navbar /><main className="page" style={{ maxWidth: 900, margin: "0 auto", padding: "40px 20px" }}>{policyLinks}<h1>Terms & Conditions</h1><p style={{ color: "#666", marginBottom: 20 }}>Last updated: 2026-09-08</p>
    <h2>Who we are</h2><p>“RESYIN Publications”, “we”, “us”, and “our” refer to the business operating this website. Our support email is <a href="mailto:info@resyinpublications.com">info@resyinpublications.com</a> and our support phone/WhatsApp numbers are +2349041441646 and +2348034621513.</p>
    <h2>Using this website</h2><p>You may use this website to browse, purchase products, manage your account, and contact support for lawful personal purposes. You must provide accurate contact and delivery information and must not misuse the website, interfere with its security, or use another person’s account without permission.</p>
    <h2>Products and product information</h2><p>We aim to show accurate product descriptions, images, prices, availability, and product information. Product images are illustrative where stated and colours may vary slightly by screen. Only products shown as available can be ordered. If we discover a material pricing, stock, or listing error before fulfilment, we may cancel the affected order and will notify and refund you where payment has been received.</p>
    <h2>Books and author content</h2><p>Book descriptions identify the title, author, and available edition where supplied. Opinions expressed in books belong to their authors. Contact us if you need help confirming a title or edition before ordering.</p>
    <h2>Prices, orders, and payment</h2><p>Product prices and checkout totals are displayed in Nigerian naira (NGN). The final amount, including the applicable delivery fee, is shown before you submit payment. We use Paystack to process payments; we do not receive or store your full card details. An order is accepted only when payment is successfully authorised and we confirm the order. We may decline or cancel an order where payment fails, fraud is reasonably suspected, stock is unavailable, or a material listing error has occurred.</p>
    <h2>Delivery</h2><p>Delivery options, charges, service, and estimated delivery period depend on the destination selected at checkout. Delivery estimates are not guaranteed arrival dates and may be affected by logistics, weather, public holidays, customs, or events outside our reasonable control. You must provide a complete and accurate delivery address and reachable contact number. Contact us promptly if an order is delayed, damaged, incomplete, or incorrect.</p>
    <h2>Returns and refunds</h2><p>Our <a href="/refund-policy">Refund & Returns Policy</a> explains eligibility, the return process, costs, and refund timing. It forms part of these terms and does not limit any rights you have under applicable law.</p>
    <h2>Third-party services and links</h2><p>Payment processing, delivery, social media, and other third-party services may have their own terms and privacy notices. We are not responsible for third-party content or services outside our reasonable control.</p>
    <h2>Changes and governing law</h2><p>We may update these terms when our business, products, or legal obligations change. The version published on this page applies from its “Last updated” date. These terms are governed by the laws of Nigeria, without limiting mandatory consumer protections that apply to you.</p>
    <h2>Contact us</h2><p>For questions about these terms or an order, contact <a href="mailto:info@resyinpublications.com">info@resyinpublications.com</a>, WhatsApp +2349041441646 or +2348034621513, or use the <a href="/contact">Contact Support</a> page.</p>
  </main></>;
}
