// Maps book subjects to shipping category codes. Keep labels aligned with the client category options.
module.exports = {
  "Academic & Professional": "books",
  "Agriculture & Farming": "books",
  "Arts & Photography": "books",
  "Biographies & Memoirs": "books",
  "Business & Leadership": "books",
  "Business & Money": "books",
  "Children & Education": "books",
  "Children's Books": "books",
  "Children's Handbooks": "books",
  "Christian Books & Bibles": "books",
  "Comics, Manga & Graphic Novels": "books",
  "Computers & Technology": "books",
  "Cookbooks, Food & Wine": "books",
  "Crafts, Hobbies & Home": "books",
  "Dictionaries & Encyclopedias": "books",
  "Education & Teaching": "books",
  "Engineering & Transportation": "books",
  "Environment & Sustainability": "books",
  "Food and Beverages": "books",
  "General Interest": "books",
  "Health, Fitness & Dieting": "books",
  "History": "books",
  "History & Society": "books",
  "Humor & Entertainment": "books",
  "Languages & Linguistics": "books",
  "Law": "books",
  "LGBTQ+ Books": "books",
  "Literature & Fiction": "books",
  "Medical Books": "books",
  "Mystery, Thriller & Suspense": "books",
  "Parenting & Relationships": "books",
  "Philosophy": "books",
  "Poetry & Drama": "books",
  "Politics & Public Administration": "books",
  "Politics & Social Sciences": "books",
  "Reference": "books",
  "Religion & Spirituality": "books",
  "Romance": "books",
  "Science & Math": "books",
  "Science Fiction & Fantasy": "books",
  "Self-Help": "books",
  "Sports & Outdoors": "books",
  "Teen & Young Adult": "books",
  "Test Preparation": "books",
  "Textbooks": "books",
  "Travel": "books",
  "True Crime": "books",
  "Workbooks & Activity Books": "books"
};
