// Book subjects for catalog browsing and book submission forms.
const PRODUCT_CATEGORY_OPTIONS = [
  "Academic & Professional",
  "Agriculture & Farming",
  "Arts & Photography",
  "Biographies & Memoirs",
  "Business & Leadership",
  "Business & Money",
  "Children & Education",
  "Children's Books",
  "Children's Handbooks",
  "Christian Books & Bibles",
  "Comics, Manga & Graphic Novels",
  "Computers & Technology",
  "Cookbooks, Food & Wine",
  "Crafts, Hobbies & Home",
  "Dictionaries & Encyclopedias",
  "Education & Teaching",
  "Engineering & Transportation",
  "Environment & Sustainability",
  "Food and Beverages",
  "General Interest",
  "Health, Fitness & Dieting",
  "History",
  "History & Society",
  "Humor & Entertainment",
  "Languages & Linguistics",
  "Law",
  "LGBTQ+ Books",
  "Literature & Fiction",
  "Medical Books",
  "Mystery, Thriller & Suspense",
  "Parenting & Relationships",
  "Philosophy",
  "Poetry & Drama",
  "Politics & Public Administration",
  "Politics & Social Sciences",
  "Reference",
  "Religion & Spirituality",
  "Romance",
  "Science & Math",
  "Science Fiction & Fantasy",
  "Self-Help",
  "Sports & Outdoors",
  "Teen & Young Adult",
  "Test Preparation",
  "Textbooks",
  "Travel",
  "True Crime",
  "Workbooks & Activity Books"
];
export default PRODUCT_CATEGORY_OPTIONS;
